### ISSUE TITLE
tail is not portable

### ISSUE THREAD

**Issue by stupinva** [michaelforney/sbase#7]
tail is not portable, used sys/inotify.h that missing on NetBSD:

```
$ make
cc -std=c99 -Wall -pedantic -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_XOPEN_SOURCE=700 -D_FILE_OFFSET_BITS=64 -D_NETBSD_SOURCE -o tail.o -c tail.c
tail.c:2:10: fatal error: sys/inotify.h: No such file or directory
 #include <sys/inotify.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
*** Error code 1

Stop.
make: stopped in /home/stupin/sbase

```

**Comment by michaelforney** [comment]
This repository is primarily for the oasis sbase branch. It was supposed to be in the `oasis` branch, but it looks like I may have accidentally pushed to `master`.

Either way, k0ga is now maintaining sbase, and the official upstream repository is https://git.suckless.org/sbase/. I dropped "mirror" from the repository description to prevent further confusion, and updated `master` to the latest upstream commit.
